export default {
    key: 'casualties',
    data: {
        data: [
            {
                parentName: '西城区',
                death: 79,
                injured: 60,
                miss: 69,
                damage: 76,
                poptotal: 1232757,
                lost: 69,
                x: 116.35581226,
                y: 39.87521582,
                id: '110102',
                child: [
                    {
                        town: '西城区',
                        village: '白纸坊街道',
                        id: '11010201995737',
                        death: 0,
                        injured: 4,
                        miss: 1,
                        damage: 2,
                        lost: 7,
                        x: 116.35581226,
                        y: 39.87521582,
                        poptotal: 95737,
                    },
                    {
                        town: '西城区',
                        village: '牛街街道',
                        id: '11010201851877',
                        death: 8,
                        injured: 9,
                        miss: 0,
                        damage: 5,
                        lost: 4,
                        x: 116.35574273,
                        y: 39.8849606,
                        poptotal: 51877,
                    },
                    {
                        town: '西城区',
                        village: '陶然亭街道',
                        id: '11010201643455',
                        death: 4,
                        injured: 8,
                        miss: 9,
                        damage: 8,
                        lost: 0,
                        x: 116.37434512,
                        y: 39.87836985,
                        poptotal: 43455,
                    },
                    {
                        town: '西城区',
                        village: '广安门外街道',
                        id: '110102020179536',
                        death: 0,
                        injured: 0,
                        miss: 3,
                        damage: 5,
                        lost: 7,
                        x: 116.33087496,
                        y: 39.88441453,
                        poptotal: 179536,
                    },
                    {
                        town: '西城区',
                        village: '广安门内街道',
                        id: '11010201773692',
                        death: 8,
                        injured: 3,
                        miss: 5,
                        damage: 3,
                        lost: 5,
                        x: 116.35577912,
                        y: 39.893187,
                        poptotal: 73692,
                    },
                    {
                        town: '西城区',
                        village: '椿树街道',
                        id: '11010201500030547',
                        death: 1,
                        injured: 8,
                        miss: 6,
                        damage: 6,
                        lost: 1,
                        x: 116.37335469,
                        y: 39.89319931,
                        poptotal: 30547,
                    },
                    {
                        town: '西城区',
                        village: '天桥街道',
                        id: '11010201400046385',
                        death: 9,
                        injured: 0,
                        miss: 8,
                        damage: 9,
                        lost: 0,
                        x: 116.38645531,
                        y: 39.87999297,
                        poptotal: 46385,
                    },
                    {
                        town: '西城区',
                        village: '大栅栏街道',
                        id: '11010201300036997',
                        death: 5,
                        injured: 6,
                        miss: 5,
                        damage: 9,
                        lost: 4,
                        x: 116.38474496,
                        y: 39.89366965,
                        poptotal: 36997,
                    },
                    {
                        town: '西城区',
                        village: '月坛街道',
                        id: '110102007116543',
                        death: 9,
                        injured: 7,
                        miss: 5,
                        damage: 4,
                        lost: 5,
                        x: 116.33948174,
                        y: 39.90712744,
                        poptotal: 116543,
                    },
                    {
                        town: '西城区',
                        village: '金融街街道',
                        id: '11010201167888',
                        death: 6,
                        injured: 3,
                        miss: 8,
                        damage: 9,
                        lost: 9,
                        x: 116.35880759,
                        y: 39.91033134,
                        poptotal: 67888,
                    },
                    {
                        town: '西城区',
                        village: '西长安街街道',
                        id: '11010200151477',
                        death: 5,
                        injured: 0,
                        miss: 7,
                        damage: 3,
                        lost: 8,
                        x: 116.37730624,
                        y: 39.909403,
                        poptotal: 51477,
                    },
                    {
                        town: '西城区',
                        village: '展览路街道',
                        id: '110102009130925',
                        death: 9,
                        injured: 3,
                        miss: 0,
                        damage: 2,
                        lost: 4,
                        x: 116.33855733,
                        y: 39.93035266,
                        poptotal: 130925,
                    },
                    {
                        town: '西城区',
                        village: '新街口街道',
                        id: '11010200395497',
                        death: 8,
                        injured: 2,
                        miss: 5,
                        damage: 4,
                        lost: 8,
                        x: 116.35844334,
                        y: 39.9336189,
                        poptotal: 95497,
                    },
                    {
                        town: '西城区',
                        village: '什刹海街道',
                        id: '11010201295433',
                        death: 6,
                        injured: 1,
                        miss: 7,
                        damage: 3,
                        lost: 4,
                        x: 116.37847991,
                        y: 39.93369201,
                        poptotal: 95433,
                    },
                    {
                        town: '西城区',
                        village: '德胜街道',
                        id: '110102010116768',
                        death: 1,
                        injured: 6,
                        miss: 0,
                        damage: 4,
                        lost: 3,
                        x: 116.37565036,
                        y: 39.95843999,
                        poptotal: 116768,
                    },
                ],
            },
            {
                parentName: '丰台区',
                death: 105,
                injured: 80,
                miss: 103,
                damage: 101,
                poptotal: 3344919,
                lost: 106,
                x: 116.35984272,
                y: 39.86261546,
                id: '110106',
                child: [
                    {
                        town: '丰台区',
                        village: '右安门街道',
                        id: '11010600183936',
                        death: 7,
                        injured: 5,
                        miss: 4,
                        damage: 9,
                        lost: 2,
                        x: 116.35984272,
                        y: 39.86261546,
                        poptotal: 83936,
                    },
                    {
                        town: '丰台区',
                        village: '西罗园街道',
                        id: '11010600383430',
                        death: 1,
                        injured: 1,
                        miss: 6,
                        damage: 7,
                        lost: 3,
                        x: 116.37862754,
                        y: 39.85462306,
                        poptotal: 83430,
                    },
                    {
                        town: '丰台区',
                        village: '马家堡街道',
                        id: '110106015119595',
                        death: 8,
                        injured: 0,
                        miss: 4,
                        damage: 1,
                        lost: 5,
                        x: 116.35895852,
                        y: 39.84173114,
                        poptotal: 119595,
                    },
                    {
                        town: '丰台区',
                        village: '太平桥街道',
                        id: '11010600263588',
                        death: 5,
                        injured: 9,
                        miss: 9,
                        damage: 7,
                        lost: 4,
                        x: 116.31097495,
                        y: 39.88485288,
                        poptotal: 63588,
                    },
                    {
                        town: '丰台区',
                        village: '大红门街道',
                        id: '110106004193382',
                        death: 8,
                        injured: 2,
                        miss: 1,
                        damage: 3,
                        lost: 6,
                        x: 116.3861077,
                        y: 39.83665633,
                        poptotal: 193382,
                    },
                    {
                        town: '丰台区',
                        village: '卢沟桥镇',
                        id: '110106017173690',
                        death: 8,
                        injured: 3,
                        miss: 8,
                        damage: 5,
                        lost: 4,
                        x: 116.27652054,
                        y: 39.87583542,
                        poptotal: 173690,
                    },
                    {
                        town: '丰台区',
                        village: '丰台街道',
                        id: '110106009144185',
                        death: 4,
                        injured: 3,
                        miss: 0,
                        damage: 5,
                        lost: 7,
                        x: 116.27847653,
                        y: 39.85328826,
                        poptotal: 144185,
                    },
                    {
                        town: '丰台区',
                        village: '方庄镇',
                        id: '11010601300083454',
                        death: 1,
                        injured: 9,
                        miss: 7,
                        damage: 2,
                        lost: 2,
                        x: 116.42749488,
                        y: 39.86369204,
                        poptotal: 83454,
                    },
                    {
                        town: '丰台区',
                        village: '花乡镇',
                        id: '110106018143041',
                        death: 3,
                        injured: 3,
                        miss: 9,
                        damage: 3,
                        lost: 9,
                        x: 116.31579534,
                        y: 39.81543201,
                        poptotal: 143041,
                    },
                    {
                        town: '丰台区',
                        village: '新村街道',
                        id: '110106010159357',
                        death: 3,
                        injured: 6,
                        miss: 7,
                        damage: 4,
                        lost: 9,
                        x: 116.29228981,
                        y: 39.82715362,
                        poptotal: 159357,
                    },
                    {
                        town: '丰台区',
                        village: '和义街道',
                        id: '11010601640477',
                        death: 4,
                        injured: 9,
                        miss: 5,
                        damage: 8,
                        lost: 9,
                        x: 116.39157027,
                        y: 39.81555269,
                        poptotal: 40477,
                    },
                    {
                        town: '丰台区',
                        village: '东铁匠营街道',
                        id: '110106007144894',
                        death: 4,
                        injured: 3,
                        miss: 2,
                        damage: 6,
                        lost: 7,
                        x: 116.43078366,
                        y: 39.84866425,
                        poptotal: 144894,
                    },
                    {
                        town: '丰台区',
                        village: '南苑镇',
                        id: '110106019000140155',
                        death: 7,
                        injured: 1,
                        miss: 4,
                        damage: 6,
                        lost: 9,
                        x: 116.3542438,
                        y: 39.80270348,
                        poptotal: 140155,
                    },
                    {
                        town: '丰台区',
                        village: '卢沟桥街道',
                        id: '110106008181666',
                        death: 8,
                        injured: 8,
                        miss: 1,
                        damage: 7,
                        lost: 9,
                        x: 116.25740332,
                        y: 39.88987798,
                        poptotal: 181666,
                    },
                    {
                        town: '丰台区',
                        village: '南苑街道',
                        id: '11010600548076',
                        death: 9,
                        injured: 0,
                        miss: 5,
                        damage: 6,
                        lost: 0,
                        x: 116.38625675,
                        y: 39.79206226,
                        poptotal: 48076,
                    },
                    {
                        town: '丰台区',
                        village: '东高地街道',
                        id: '11010600644912',
                        death: 2,
                        injured: 4,
                        miss: 4,
                        damage: 0,
                        lost: 1,
                        x: 116.40942153,
                        y: 39.79999164,
                        poptotal: 44912,
                    },
                    {
                        town: '丰台区',
                        village: '宛平城镇',
                        id: '11010601449180',
                        death: 8,
                        injured: 4,
                        miss: 7,
                        damage: 4,
                        lost: 0,
                        x: 116.2369086,
                        y: 39.83003412,
                        poptotal: 49180,
                    },
                    {
                        town: '丰台区',
                        village: '长辛店街道',
                        id: '11010601180639',
                        death: 0,
                        injured: 1,
                        miss: 9,
                        damage: 7,
                        lost: 9,
                        x: 116.19792897,
                        y: 39.8244492,
                        poptotal: 80639,
                    },
                    {
                        town: '丰台区',
                        village: '长辛店镇',
                        id: '11010610047986',
                        death: 0,
                        injured: 1,
                        miss: 6,
                        damage: 9,
                        lost: 2,
                        x: 116.1514669,
                        y: 39.83865663,
                        poptotal: 47986,
                    },
                    {
                        town: '丰台区',
                        village: '云岗街道',
                        id: '11010601232711',
                        death: 9,
                        injured: 1,
                        miss: 5,
                        damage: 0,
                        lost: 1,
                        x: 116.14600798,
                        y: 39.8179006,
                        poptotal: 32711,
                    },
                    {
                        town: '丰台区',
                        village: '王佐镇',
                        id: '11010610153808',
                        death: 6,
                        injured: 7,
                        miss: 0,
                        damage: 2,
                        lost: 8,
                        x: 116.11603887,
                        y: 39.81001133,
                        poptotal: 53808,
                    },
                ],
            },
        ],
        injured: '1216',
        damage: '1302',
        death: '1447',
    },
};
