import { SymbolMap } from '../../SymbolConfig';
const ResourceSymbolMap: any = {
  'default': SymbolMap.DEFAULT,
  'ANJIAN_DAGCHEMENT※DangerousChemical': SymbolMap.HAZARDOUS,
  'firework': SymbolMap.FIREWORKENT,
  'airport': SymbolMap.AIRPORT,
  'forestfireteam': SymbolMap.SENFORERescueTeam,
  'firepreventionrepository': SymbolMap.SENFORE,
  'for_watersource': SymbolMap.SENFORE,
  'for_waterport': SymbolMap.SENFORE,
  'FOR_WATERSOURCE※04': SymbolMap.SENFORE,
  'for_watersourceport': SymbolMap.SENFORE,
  'metalnonmetal': SymbolMap.ANJIAN_METALNONMETAL,
  'ANJIAN_OILGASFIELD※01': SymbolMap.ANJIAN_OILGASFIELD1,
  'ANJIAN_OILGASFIELD※02': SymbolMap.ANJIAN_OILGASFIELD2,
  'riverStation': SymbolMap.riverStation,
  'limitOfReservoir': SymbolMap.limitOfReservoir,
  'superRainMeasuringStation': SymbolMap.superRainMeasuringStation,
  'heavyRainMeasuringStation': SymbolMap.heavyRainMeasuringStation,
  'rainMeasuringStation': SymbolMap.rainMeasuringStation,
  'fireworkhouse': SymbolMap.SENFORE,
  'forest_fire_prevention_natural_reserve': SymbolMap.forest_fire_prevention_natural_reserve,
  'fores_fire_prevention_important_place': SymbolMap.fores_fire_prevention_important_place,
  'forest_fire_prevention': SymbolMap.forest_fire_prevention,
  'forest_fire_prevention_barrier_strip': SymbolMap.forest_fire_prevention_barrier_strip,
  'forest_fire_prevention_meteorological_monitoring_station': SymbolMap.forest_fire_prevention_meteorological_monitoring_station,
};
export default ResourceSymbolMap;
